config/routes.rb
Rails.application.routes.draw do
# resources :order_items
  # get 'addtocart#show'
  get 'home/index'
  get 'carts/adddata'
  resources :carts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'carts#index'

  post "carts/add_to_cart/:id", to: "carts#add_to_cart", as: "add_to_cart"
  delete "carts/remove_from_cart/:id", to: "carts#remove_from_cart", as: "remove_from_cart"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 5}
    has_one_attached :avatar
end

app/models/image_element.rb
class ImageElement < ApplicationRecord
  belongs_to :page
end

app/controllers/addtocart_controller.rb
class AddtocartController < ApplicationController
  # def show
  #   @order_items = current_order.order_items
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # include ApplicationHelper
    before_action :initialize_session 
    before_action :load_product

    private
    def initialize_session
        session[:product] ||= []
    end
    def load_product
        @product =Cart.find(session[:product])
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  def add_to_cart
    id = params[:id].to_i
    session[:product] << id unless session[:product].include?(id)
    redirect_to carts_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:product].delete(id)
    redirect_to carts_path
  end

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
    # @order_item = current_order.order_items.new
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    #this  section is used to permit the data of title ,description and price data to perform actions
    def cart_params
      params.require(:cart).permit(:title,:description,:price,:avatar)
      # @cart.avatar.attach(params[])
      
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:cart_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/helpers/addtocart_helper.rb
module AddtocartHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/carts/_cart.html.erb
<%# <div class="card-group"> %>

<div id="<%= dom_id cart %>" >


    
      <div class="card-body">
       <% if cart.avatar.attached? %>
  <%= image_tag cart.avatar, style: "width:300px; "%>
  <%end%>
      <h5 class="card-title"><%= cart.title %></h5>
        <p class="card-text"><%= cart.description %></p> 
         <p class="card-text"><%= cart.price %></p> 
      </div>
      

  </div>
  </div>


    

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
    <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
    <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
  <% if cart.avatar.attached? %>
  <%= image_tag cart.avatar, style: "width:300px; display:block"%>
  <%end%>
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/adddata.html.erb
  
     
      <% @product.each do |cart| %>
      <div class="card border-success mb-3" style="max-width: 18rem;">
  <div class="card-header bg-transparent border-success">product Id: <%= cart.id %></div>
  <div class="card-body text-success">
    <h5 class="card-title"><%= cart.title %></h5>
    <p class="card-text"><%= cart.description%></p>
  </div>
  <div class="card-footer bg-transparent border-success"><%= cart.price%></div>
</div>
 <%= button_to "Remove from cart", remove_from_cart_path(@product), method: :delete ,class:"btn btn-danger" %> 
 <% end %>
      
      <hr>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%# <%= link_to "Show this cart", @cart ,class:"btn btn-outline-success" %>
  <%= link_to "Back to product", carts_path ,class:"btn btn-outline-dark"%>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>ecommerce</h1>

<%# <div class="row row-cols-1 row-cols-md-3"> %>
<br>
<div class="float-right">
<%= link_to "New cart", new_cart_path ,class:"btn btn-outline-success" %>
</div>
<br>
<br>

<div id="carts"   class="card-group">
  <% @carts.each do |cart| %>
<div class="col-sm-4">
<div class="card">
  
     
        <%= render cart %>
   

   <%= link_to "view details", cart ,class:"btn btn-outline-info"%>
    
    
    </div>
  <% end %>
 
</div>

   <%# </div> %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to product", carts_path ,class:"btn btn-outline-secondary" %>
</div>

app/views/carts/show.html.erb
  <p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <%= button_to "Delete", @cart, method: :delete ,class:"btn btn-danger float-right"%>
<%= render @cart %>
   <%= link_to "Edit ", edit_cart_path(@cart) ,class:"btn btn-primary" %> |
  <%= link_to "Back to product", carts_path ,class:"btn btn-dark" %>|
  <%# <%= link_to "Add to cart", home_index_path ,class:"btn btn-dark" %> 
    <%# <% if @product.include?(@cart) %> 
            <%# <%= button_to "Remove from cart", remove_from_cart_path(@cart), method: :delete %> 
          <%# <% else %> 
            <%= button_to "Add to cart", add_to_cart_path(@cart) ,class:"btn btn-dark" %>
          <%# <% end %> 

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
<%= link_to 'Home' ,root_path ,class:"navbar-brand" %>
    
    <form class="d-flex">
      <i class="fa-solid fa-cart-plus"><%= link_to 'Add to cart' ,carts_adddata_path ,class:"navbar-brand" %></i>
    </form>
  </div>
</nav>

app/views/home/index.html.erb
<h1>this Add tocart page home page</h1>
<%# <%= render @cart %>  %>

<div class="card-group">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Cartapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
   



  
   <div class="container">
   <br><br>
   <%= render 'home/header'%>

    <%= yield %>
   </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>